name: myapp
description: "A new Flutter project."

# Prevent accidental publication to pub.dev for private packages.
publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  intl_utils: ^2.8.7
  url_launcher: ^6.3.1
  dwds: ^24.1.0
  elegant_notification: ^2.4.0
  supabase_flutter: ^2.8.1
  image_picker: ^1.1.2
  file_picker: ^8.1.4
  uuid: ^4.5.1
  http: ^1.2.2
  image: ^4.3.0

  # Cupertino Icons for iOS-style icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/tahura.png"

  # Recommended linting package for better coding practices
flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  # Example for adding custom fonts (uncomment and adjust as needed)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
